// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	feed "github.com/me2seeks/echo-hub/app/search/cmd/api/internal/handler/feed"
	user "github.com/me2seeks/echo-hub/app/search/cmd/api/internal/handler/user"
	"github.com/me2seeks/echo-hub/app/search/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// search feeds
				Method:  http.MethodPost,
				Path:    "/:keyword",
				Handler: feed.SearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/search/feeds"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// search users
				Method:  http.MethodPost,
				Path:    "/:keyword",
				Handler: user.SearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/search/users"),
	)
}
