// Code generated by goctl. DO NOT EDIT.
package types

import "github.com/me2seeks/echo-hub/common/upload"

type Comment struct {
	ID          int64  `json:"id"`
	FeedID      int64  `json:"feedID"`
	UserID      int64  `json:"userID"`
	Content     string `json:"content"`
	Media0      string `json:"media0"`
	Media1      string `json:"media1"`
	Media2      string `json:"media2"`
	Media3      string `json:"media3"`
	Create_time int64  `json:"create_time"`
}

type CreateCommentReq struct {
	CommentID int64  `json:"comment_id"`
	Content   string `json:"content"`
	Media0    string `json:"media0"`
	Media1    string `json:"media1"`
	Media2    string `json:"media2"`
	Media3    string `json:"media3"`
}

type CreateCommentResp struct {
	ID int64 `json:"id"`
}

type CreateFeedCommentReq struct {
	FeedID  int64  `path:"feedID"`
	Content string `json:"content"`
	Media0  string `json:"media0"`
	Media1  string `json:"media1"`
	Media2  string `json:"media2"`
	Media3  string `json:"media3"`
}

type CreateFeedCommentResp struct {
	ID int64 `json:"id"`
}

type CreateFeedReq struct {
	Content string `json:"content"`
	Media0  string `json:"media0"`
	Media1  string `json:"media1"`
	Media2  string `json:"media2"`
	Media3  string `json:"media3"`
}

type CreateFeedResp struct {
	ID int64 `json:"id"`
}

type DeleteCommentReq struct {
	ID       int64 `json:"id"`
	ParentID int64 `json:"parent_id"`
}

type DeleteCommentResp struct {
}

type DeleteFeedReq struct {
	ID int64 `json:"id"`
}

type DeleteFeedResp struct {
}

type Feed struct {
	ID          int64  `json:"id"`
	UserID      int64  `json:"userID"`
	Content     string `json:"content"`
	Media0      string `json:"media0"`
	Media1      string `json:"media1"`
	Media2      string `json:"media2"`
	Media3      string `json:"media3"`
	Create_time int64  `json:"create_time"`
}

type GetCommentsByPageReq struct {
	CommentID int64 `path:"commentID"`
	Page      int64 `form:"page"`
	PageSize  int64 `form:"page_size"`
}

type GetCommentsByPageResp struct {
	Comments []Comment `json:"comment"`
	Total    int64     `json:"total"`
}

type GetFeedCommentsByPageReq struct {
	FeedID   int64 `path:"feedID"`
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type GetFeedCommentsByPageResp struct {
	Comments []Comment `json:"comment"`
	Total    int64     `json:"total"`
}

type GetFeedsByPageReq struct {
	UserID   int64 `path:"userID"`
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type GetFeedsByPageResp struct {
	Feeds []Feed `json:"feed"`
	Total int64  `json:"total"`
}

type GetFollowingFeedsByPageReq struct {
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type GetFollowingFeedsByPageResp struct {
	Feeds []Feed `json:"feed"`
	Total int64  `json:"total"`
}

type Object struct {
	FileName string            `json:"fileName"`
	FileType upload.ObjectType `json:"fileType"`
}

type PresignReq struct {
	Objects []Object `json:"objects"`
}

type PresignResp struct {
	Urls []string `json:"urls"`
}
