// Code generated by goctl. DO NOT EDIT.
package types

type Feed struct {
	Id        string `json:"id"`
	Content   string `json:"content"`
	UserID    string `json:"userID"`
	Media0    string `json:"media0"`
	Media1    string `json:"media1"`
	Media2    string `json:"media2"`
	Media3    string `json:"media3"`
	CreatTime int64  `json:"createTime"`
}

type SearchFeedsResp struct {
	Feeds []Feed `json:"feeds"`
}

type SearchReq struct {
	Keyword  string `form:"keyword"`
	Page     int64  `form:"page"`
	PageSize int64  `form:"pageSize"`
}

type SearchUsersResp struct {
	Users []User `json:"users"`
}

type User struct {
	Id         string `json:"id"`
	Nickname   string `json:"nickname"`
	Handle     string `json:"handle"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"createTime"`
}
