// Code generated by goctl. DO NOT EDIT.
package types

type SearchFeedsResp struct {
	Feeds []Feed `json:"feeds"`
}

type SearchReq struct {
	Keyword  string `path:"keyword"`
	Page     int32  `form:"page"`
	PageSize int32  `form:"pageSize"`
}

type SearchUsersResp struct {
	Users []User `json:"users"`
}

type User struct {
	Id       int64  `json:"id"`
	Nickname string `json:"nickname"`
	Handle   string `json:"Handle"`
}

type Feed struct {
	Id      int64  `json:"id"`
	Content string `json:"content"`
	UserID  int64  `json:"userID"`
	Media0  string `json:"media0"`
	Media1  string `json:"media1"`
	Media2  string `json:"media2"`
	Media3  string `json:"media3"`
	Created int64  `json:"created"`
}
