// Code generated by goctl. DO NOT EDIT.
// Source: interaction.proto

package server

import (
	"context"

	"github.com/me2seeks/echo-hub/app/interaction/cmd/rpc/internal/logic"
	"github.com/me2seeks/echo-hub/app/interaction/cmd/rpc/internal/svc"
	"github.com/me2seeks/echo-hub/app/interaction/cmd/rpc/pb"
)

type InteractionServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedInteractionServer
}

func NewInteractionServer(svcCtx *svc.ServiceContext) *InteractionServer {
	return &InteractionServer{
		svcCtx: svcCtx,
	}
}

func (s *InteractionServer) CreateLike(ctx context.Context, in *pb.CreateLikeReq) (*pb.CreateLikeResp, error) {
	l := logic.NewCreateLikeLogic(ctx, s.svcCtx)
	return l.CreateLike(in)
}

func (s *InteractionServer) DeleteLike(ctx context.Context, in *pb.DeleteLikeReq) (*pb.DeleteLikeResp, error) {
	l := logic.NewDeleteLikeLogic(ctx, s.svcCtx)
	return l.DeleteLike(in)
}

func (s *InteractionServer) GetLikeCount(ctx context.Context, in *pb.GetLikeCountReq) (*pb.GetLikeCountResp, error) {
	l := logic.NewGetLikeCountLogic(ctx, s.svcCtx)
	return l.GetLikeCount(in)
}

func (s *InteractionServer) GetLikeStatus(ctx context.Context, in *pb.GetLikeStatusReq) (*pb.GetLikeStatusResp, error) {
	l := logic.NewGetLikeStatusLogic(ctx, s.svcCtx)
	return l.GetLikeStatus(in)
}
