// Code generated by goctl. DO NOT EDIT.
package types

type GetContentCounterReq struct {
	ID int64 `path:"id"`
}

type GetContentCounterResp struct {
	CommentCount int64 `json:"commentCount"`
	LikeCount    int64 `json:"likeCount"`
	ViewCount    int64 `json:"viewCount"`
}

type GetUserCounterReq struct {
	UserID int64 `path:"id"`
}

type GetUserCounterResp struct {
	FollowingCount int64 `json:"followingCount"`
	FollowerCount  int64 `json:"followerCount"`
	FeedCount      int64 `json:"feedCount"`
}
