// Code generated by goctl. DO NOT EDIT.
package types

type FollowReq struct {
	UserId int64 `json:"userId"`
}

type FollowResp struct {
}

type FollowersReq struct {
	UserId int64 `json:"userId"`
}

type FollowersResp struct {
	Followers []int64 `json:"followers"`
}

type FollowingReq struct {
	UserId int64 `json:"userId"`
}

type FollowingResp struct {
	Followings []int64 `json:"following"`
}

type UnfollowReq struct {
	UserId int64 `json:"userId"`
}

type UnfollowResp struct {
}
