// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/me2seeks/echo-hub/common/globalkey"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	commentLikesFieldNames          = builder.RawFieldNames(&CommentLikes{})
	commentLikesRows                = strings.Join(commentLikesFieldNames, ",")
	commentLikesRowsExpectAutoSet   = strings.Join(stringx.Remove(commentLikesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	commentLikesRowsWithPlaceHolder = strings.Join(stringx.Remove(commentLikesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCommentLikesIdPrefix              = "cache:commentLikes:id:"
	cacheCommentLikesUserIdContentIdPrefix = "cache:commentLikes:userId:contentId:"
)

type (
	commentLikesModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *CommentLikes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CommentLikes, error)
		FindOneByUserIdContentId(ctx context.Context, userId int64, contentId int64) (*CommentLikes, error)
		Update(ctx context.Context, session sqlx.Session, data *CommentLikes) (sql.Result, error)
		UpdateWithVersion(ctx context.Context, session sqlx.Session, data *CommentLikes) error
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		DeleteSoft(ctx context.Context, session sqlx.Session, data *CommentLikes) error
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*CommentLikes, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*CommentLikes, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*CommentLikes, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*CommentLikes, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*CommentLikes, error)
		Delete(ctx context.Context, session sqlx.Session, id int64) error

		DeleteByUserIdContentId(ctx context.Context, session sqlx.Session, userID, contentId int64) error
	}

	defaultCommentLikesModel struct {
		sqlc.CachedConn
		table string
	}

	CommentLikes struct {
		Id        int64     `db:"id"`
		UserId    int64     `db:"user_id"`
		ContentId int64     `db:"content_id"`
		CreateAt  time.Time `db:"create_at"`
		UpdateAt  time.Time `db:"update_at"`
		DeleteAt  time.Time `db:"delete_at"`
		DelState  int64     `db:"del_state"`
		Version   uint64    `db:"version"` // 版本号
	}
)

func newCommentLikesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCommentLikesModel {
	return &defaultCommentLikesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`comment_likes`",
	}
}

func (m *defaultCommentLikesModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	commentLikesIdKey := fmt.Sprintf("%s%v", cacheCommentLikesIdPrefix, id)
	commentLikesUserIdContentIdKey := fmt.Sprintf("%s%v:%v", cacheCommentLikesUserIdContentIdPrefix, data.UserId, data.ContentId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, id)
		}
		return conn.ExecCtx(ctx, query, id)
	}, commentLikesIdKey, commentLikesUserIdContentIdKey)
	return err
}

func (m *defaultCommentLikesModel) DeleteByUserIdContentId(ctx context.Context, session sqlx.Session, userID, contentId int64) error {
	data, err := m.FindOneByUserIdContentId(ctx, userID, contentId)
	if err != nil {
		return err
	}

	commentLikesIdKey := fmt.Sprintf("%s%v", cacheCommentLikesIdPrefix, data.Id)
	commentLikesUserIdContentIdKey := fmt.Sprintf("%s%v:%v", cacheCommentLikesUserIdContentIdPrefix, data.UserId, data.ContentId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		if session != nil {
			return session.ExecCtx(ctx, query, data.Id)
		}
		return conn.ExecCtx(ctx, query, data.Id)
	}, commentLikesIdKey, commentLikesUserIdContentIdKey)
	return err
}

func (m *defaultCommentLikesModel) FindOne(ctx context.Context, id int64) (*CommentLikes, error) {
	commentLikesIdKey := fmt.Sprintf("%s%v", cacheCommentLikesIdPrefix, id)
	var resp CommentLikes
	err := m.QueryRowCtx(ctx, &resp, commentLikesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", commentLikesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id, globalkey.DelStateNo)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentLikesModel) FindOneByUserIdContentId(ctx context.Context, userId int64, contentId int64) (*CommentLikes, error) {
	commentLikesUserIdContentIdKey := fmt.Sprintf("%s%v:%v", cacheCommentLikesUserIdContentIdPrefix, userId, contentId)
	var resp CommentLikes
	err := m.QueryRowIndexCtx(ctx, &resp, commentLikesUserIdContentIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `content_id` = ? and del_state = ? limit 1", commentLikesRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, contentId, globalkey.DelStateNo); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCommentLikesModel) Insert(ctx context.Context, session sqlx.Session, data *CommentLikes) (sql.Result, error) {
	data.DeleteAt = time.Unix(0, 0)
	data.DelState = globalkey.DelStateNo
	commentLikesIdKey := fmt.Sprintf("%s%v", cacheCommentLikesIdPrefix, data.Id)
	commentLikesUserIdContentIdKey := fmt.Sprintf("%s%v:%v", cacheCommentLikesUserIdContentIdPrefix, data.UserId, data.ContentId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, commentLikesRowsExpectAutoSet)
		if session != nil {
			return session.ExecCtx(ctx, query, data.UserId, data.ContentId, data.DeleteAt, data.DelState, data.Version)
		}
		return conn.ExecCtx(ctx, query, data.UserId, data.ContentId, data.DeleteAt, data.DelState, data.Version)
	}, commentLikesIdKey, commentLikesUserIdContentIdKey)
}

func (m *defaultCommentLikesModel) Update(ctx context.Context, session sqlx.Session, newData *CommentLikes) (sql.Result, error) {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return nil, err
	}
	commentLikesIdKey := fmt.Sprintf("%s%v", cacheCommentLikesIdPrefix, data.Id)
	commentLikesUserIdContentIdKey := fmt.Sprintf("%s%v:%v", cacheCommentLikesUserIdContentIdPrefix, data.UserId, data.ContentId)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, commentLikesRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.UserId, newData.ContentId, newData.DeleteAt, newData.DelState, newData.Version, newData.Id)
		}
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ContentId, newData.DeleteAt, newData.DelState, newData.Version, newData.Id)
	}, commentLikesIdKey, commentLikesUserIdContentIdKey)
}

func (m *defaultCommentLikesModel) UpdateWithVersion(ctx context.Context, session sqlx.Session, newData *CommentLikes) error {

	oldVersion := newData.Version
	newData.Version += 1

	var sqlResult sql.Result
	var err error

	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}
	commentLikesIdKey := fmt.Sprintf("%s%v", cacheCommentLikesIdPrefix, data.Id)
	commentLikesUserIdContentIdKey := fmt.Sprintf("%s%v:%v", cacheCommentLikesUserIdContentIdPrefix, data.UserId, data.ContentId)
	sqlResult, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ? and version = ? ", m.table, commentLikesRowsWithPlaceHolder)
		if session != nil {
			return session.ExecCtx(ctx, query, newData.UserId, newData.ContentId, newData.DeleteAt, newData.DelState, newData.Version, newData.Id, oldVersion)
		}
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ContentId, newData.DeleteAt, newData.DelState, newData.Version, newData.Id, oldVersion)
	}, commentLikesIdKey, commentLikesUserIdContentIdKey)
	if err != nil {
		return err
	}
	updateCount, err := sqlResult.RowsAffected()
	if err != nil {
		return err
	}
	if updateCount == 0 {
		return ErrNoRowsUpdate
	}

	return nil
}

func (m *defaultCommentLikesModel) DeleteSoft(ctx context.Context, session sqlx.Session, data *CommentLikes) error {
	data.DelState = globalkey.DelStateYes
	data.DeleteAt = time.Now()
	if err := m.UpdateWithVersion(ctx, session, data); err != nil {
		return errors.Wrapf(errors.New("delete soft failed "), "CommentLikesModel delete err : %+v", err)
	}
	return nil
}

func (m *defaultCommentLikesModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultCommentLikesModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.QueryRowNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultCommentLikesModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*CommentLikes, error) {

	builder = builder.Columns(commentLikesRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*CommentLikes
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCommentLikesModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*CommentLikes, error) {

	builder = builder.Columns(commentLikesRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*CommentLikes
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCommentLikesModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*CommentLikes, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(commentLikesRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*CommentLikes
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultCommentLikesModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*CommentLikes, error) {

	builder = builder.Columns(commentLikesRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*CommentLikes
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCommentLikesModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*CommentLikes, error) {

	builder = builder.Columns(commentLikesRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("del_state = ?", globalkey.DelStateNo).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*CommentLikes
	err = m.QueryRowsNoCacheCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultCommentLikesModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultCommentLikesModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultCommentLikesModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheCommentLikesIdPrefix, primary)
}
func (m *defaultCommentLikesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? and del_state = ? limit 1", commentLikesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary, globalkey.DelStateNo)
}

func (m *defaultCommentLikesModel) tableName() string {
	return m.table
}
