// Code generated by goctl. DO NOT EDIT.
// Source: counter.proto

package counter

import (

	// "github.com/me2seeks/echo-hub/app/counter/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
)

type (
	Counter interface {
	}

	defaultCounter struct {
		cli zrpc.Client
	}
)

func NewCounter(cli zrpc.Client) Counter {
	return &defaultCounter{
		cli: cli,
	}
}
