// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: interaction.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Interaction_CreateLike_FullMethodName   = "/pb.interaction/createLike"
	Interaction_DeleteLike_FullMethodName   = "/pb.interaction/deleteLike"
	Interaction_GetLikeCount_FullMethodName = "/pb.interaction/getLikeCount"
)

// InteractionClient is the client API for Interaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InteractionClient interface {
	CreateLike(ctx context.Context, in *CreateLikeReq, opts ...grpc.CallOption) (*CreateLikeResp, error)
	DeleteLike(ctx context.Context, in *DeleteLikeReq, opts ...grpc.CallOption) (*DeleteLikeResp, error)
	GetLikeCount(ctx context.Context, in *GetLikeCountReq, opts ...grpc.CallOption) (*GetLikeCountResp, error)
}

type interactionClient struct {
	cc grpc.ClientConnInterface
}

func NewInteractionClient(cc grpc.ClientConnInterface) InteractionClient {
	return &interactionClient{cc}
}

func (c *interactionClient) CreateLike(ctx context.Context, in *CreateLikeReq, opts ...grpc.CallOption) (*CreateLikeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLikeResp)
	err := c.cc.Invoke(ctx, Interaction_CreateLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) DeleteLike(ctx context.Context, in *DeleteLikeReq, opts ...grpc.CallOption) (*DeleteLikeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLikeResp)
	err := c.cc.Invoke(ctx, Interaction_DeleteLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionClient) GetLikeCount(ctx context.Context, in *GetLikeCountReq, opts ...grpc.CallOption) (*GetLikeCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLikeCountResp)
	err := c.cc.Invoke(ctx, Interaction_GetLikeCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionServer is the server API for Interaction service.
// All implementations must embed UnimplementedInteractionServer
// for forward compatibility.
type InteractionServer interface {
	CreateLike(context.Context, *CreateLikeReq) (*CreateLikeResp, error)
	DeleteLike(context.Context, *DeleteLikeReq) (*DeleteLikeResp, error)
	GetLikeCount(context.Context, *GetLikeCountReq) (*GetLikeCountResp, error)
	mustEmbedUnimplementedInteractionServer()
}

// UnimplementedInteractionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInteractionServer struct{}

func (UnimplementedInteractionServer) CreateLike(context.Context, *CreateLikeReq) (*CreateLikeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLike not implemented")
}
func (UnimplementedInteractionServer) DeleteLike(context.Context, *DeleteLikeReq) (*DeleteLikeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLike not implemented")
}
func (UnimplementedInteractionServer) GetLikeCount(context.Context, *GetLikeCountReq) (*GetLikeCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikeCount not implemented")
}
func (UnimplementedInteractionServer) mustEmbedUnimplementedInteractionServer() {}
func (UnimplementedInteractionServer) testEmbeddedByValue()                     {}

// UnsafeInteractionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InteractionServer will
// result in compilation errors.
type UnsafeInteractionServer interface {
	mustEmbedUnimplementedInteractionServer()
}

func RegisterInteractionServer(s grpc.ServiceRegistrar, srv InteractionServer) {
	// If the following call pancis, it indicates UnimplementedInteractionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Interaction_ServiceDesc, srv)
}

func _Interaction_CreateLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).CreateLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_CreateLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).CreateLike(ctx, req.(*CreateLikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_DeleteLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLikeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).DeleteLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_DeleteLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).DeleteLike(ctx, req.(*DeleteLikeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interaction_GetLikeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLikeCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionServer).GetLikeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Interaction_GetLikeCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionServer).GetLikeCount(ctx, req.(*GetLikeCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Interaction_ServiceDesc is the grpc.ServiceDesc for Interaction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Interaction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.interaction",
	HandlerType: (*InteractionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createLike",
			Handler:    _Interaction_CreateLike_Handler,
		},
		{
			MethodName: "deleteLike",
			Handler:    _Interaction_DeleteLike_Handler,
		},
		{
			MethodName: "getLikeCount",
			Handler:    _Interaction_GetLikeCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interaction.proto",
}
