// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/me2seeks/echo-hub/app/counter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// get content counter
				Method:  http.MethodGet,
				Path:    "/content/:id",
				Handler: getContentCounterHandler(serverCtx),
			},
			{
				// get user counter
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: getUserCounterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/counter"),
	)
}
