// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Email    string `json:"email"`
	Handle   string `json:"handle"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type User struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	Nickname string `json:"nickname"`
	Handle   string `json:"Handle"`
	Sex      int    `json:"sex"`
	Avatar   string `json:"avatar"`
	Bio      string `json:"bio"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo struct {
		Id       int64  `json:"id"`
		Email    string `json:"email"`
		Nickname string `json:"nickname"`
		Handle   string `json:"Handle"`
		Sex      int    `json:"sex"`
		Avatar   string `json:"avatar"`
		Bio      string `json:"bio"`
	} `json:"userInfo"`
}
