// Code generated by goctl. DO NOT EDIT.
// Source: search.proto

package server

import (
	"context"

	"github.com/me2seeks/echo-hub/app/search/cmd/rpc/internal/logic"
	"github.com/me2seeks/echo-hub/app/search/cmd/rpc/internal/svc"
	"github.com/me2seeks/echo-hub/app/search/cmd/rpc/pb"
)

type SearchServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSearchServer
}

func NewSearchServer(svcCtx *svc.ServiceContext) *SearchServer {
	return &SearchServer{
		svcCtx: svcCtx,
	}
}

func (s *SearchServer) SearchUsers(ctx context.Context, in *pb.SearchReq) (*pb.SearchUsersResp, error) {
	l := logic.NewSearchUsersLogic(ctx, s.svcCtx)
	return l.SearchUsers(in)
}

func (s *SearchServer) SearchFeeds(ctx context.Context, in *pb.SearchReq) (*pb.SearchFeedsResp, error) {
	l := logic.NewSearchFeedsLogic(ctx, s.svcCtx)
	return l.SearchFeeds(in)
}
