// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	comment "github.com/me2seeks/echo-hub/app/interaction/cmd/api/internal/handler/comment"
	feed "github.com/me2seeks/echo-hub/app/interaction/cmd/api/internal/handler/feed"
	"github.com/me2seeks/echo-hub/app/interaction/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// like
				Method:  http.MethodPost,
				Path:    "/comment/:id/like",
				Handler: comment.LikeHandler(serverCtx),
			},
			{
				// unlike
				Method:  http.MethodDelete,
				Path:    "/comment/:id/like",
				Handler: comment.UnlikeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/interaction"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// like
				Method:  http.MethodPost,
				Path:    "/feed/:id/like",
				Handler: feed.LikeHandler(serverCtx),
			},
			{
				// unlike
				Method:  http.MethodDelete,
				Path:    "/feed/:id/like",
				Handler: feed.UnlikeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/interaction"),
	)
}
